language: php

env:
  global:
    - COMPOSER_ARGS=

matrix:
  fast_finish: true
  include:
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: xenial
    - php: 7.1
      dist: bionic
    - php: 7.2
      dist: bionic
    - php: 7.3
      dist: bionic
    - php: 7.4
      dist: bionic
#    - php: nightly
#      dist: bionic
#      env: COMPOSER_ARGS=--ignore-platform-reqs

before_script:
  - composer self-update --stable
  - if [ "$deps" == "low" ]; then composer update -n --prefer-dist --prefer-lowest --prefer-stable $COMPOSER_ARGS; fi
  - if [ "$deps" != "low" ]; then composer update -n --prefer-dist $COMPOSER_ARGS; fi

script:
  # - if [ "`phpenv version-name`" != "nightly" ]; then composer lint; fi
  - composer test
